export const TableDisplayNames = {
  models: 'Model',
  supportsCompletion: 'Chat Completion',
  supportsStreaming: 'Streaming',
  supportsJSON: 'JSON Output',
  supportsImages: 'Image Input',
  supportsToolCalls: 'Function Calling',
  supportsN: 'N > 1',
}

export const models = {
  openai: {
    models: [
      'gpt-5',
      'gpt-5-mini',
      'gpt-4.5-preview',
      'gpt-4.1',
      'gpt-4o',
      'gpt-4o-mini',
      'o3-mini',
      'gpt-4-turbo',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'gpt-5',
      'gpt-5-mini',
      'gpt-4.5-preview',
      'gpt-4.1',
      'gpt-4o',
      'gpt-4o-mini',
      'o3-mini',
      'gpt-4-turbo',
    ] as const,
    supportsJSON: [
      'gpt-5',
      'gpt-5-mini',
      'gpt-4.5-preview',
      'gpt-4.1',
      'gpt-4o',
      'gpt-4o-mini',
      'o3-mini',
      'gpt-4-turbo',
    ] as const,
    supportsImages: [
      'gpt-5',
      'gpt-5-mini',
      'gpt-4.5-preview',
      'gpt-4.1',
      'gpt-4o',
      'gpt-4o-mini',
      'gpt-4-turbo',
    ] as const,
    supportsToolCalls: [
      'gpt-5',
      'gpt-5-mini',
      'gpt-4.5-preview',
      'gpt-4.1',
      'gpt-4o',
      'gpt-4o-mini',
      'o3-mini',
      'gpt-4-turbo',
    ] as const,
    supportsN: true,
    generateDocs: true,
  },
  ai21: {
    models: ['jamba-instruct'] as const,
    supportsCompletion: true,
    supportsStreaming: ['jamba-instruct'] as const,
    supportsJSON: [] as const,
    supportsImages: [] as const,
    supportsToolCalls: [] as const,
    supportsN: true,
    generateDocs: true,
  },
  anthropic: {
    models: [
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-opus-4-1',
      'claude-sonnet-4',
      'claude-opus-4',
      'claude-3-7-sonnet-20250219',
      'claude-3-5-haiku-20241022',
      'claude-3-haiku-20240307',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-opus-4-1',
      'claude-sonnet-4',
      'claude-opus-4',
      'claude-3-7-sonnet-20250219',
      'claude-3-5-haiku-20241022',
      'claude-3-haiku-20240307',
    ] as const,
    supportsJSON: [] as const,
    supportsImages: [
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-opus-4-1',
      'claude-sonnet-4',
      'claude-opus-4',
      'claude-3-7-sonnet-20250219',
      'claude-3-5-haiku-20241022',
      'claude-3-haiku-20240307',
    ] as const,
    supportsToolCalls: [
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-opus-4-1',
      'claude-sonnet-4',
      'claude-opus-4',
      'claude-3-7-sonnet-20250219',
      'claude-3-5-haiku-20241022',
      'claude-3-haiku-20240307',
    ] as const,
    supportsN: false,
    generateDocs: true,
  },
  gemini: {
    models: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ] as const,
    supportsJSON: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ] as const,
    supportsImages: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ] as const,
    supportsToolCalls: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ] as const,
    supportsN: true,
    generateDocs: true,
  },
  cohere: {
    models: [
      'command-a-03-2025',
      'command-r-08-2024',
      'command-r-plus-08-2024',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'command-a-03-2025',
      'command-r-08-2024',
      'command-r-plus-08-2024',
    ] as const,
    supportsJSON: [] as const,
    supportsImages: [] as const,
    supportsToolCalls: [
      'command-a-03-2025',
      'command-r-08-2024',
      'command-r-plus-08-2024',
    ] as const,
    supportsN: false,
    generateDocs: true,
  },
  bedrock: {
    models: [
      'anthropic.claude-3-5-sonnet-20241022-v2:0',
      'anthropic.claude-3-5-haiku-20241022-v1:0',
      'cohere.command-r-plus-v1:0',
      'cohere.command-r-v1:0',
      'meta.llama3-70b-instruct-v1:0',
      'meta.llama3-8b-instruct-v1:0',
      'mistral.mistral-large-2402-v1:0',
      'amazon.titan-text-express-v1',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'anthropic.claude-3-5-sonnet-20241022-v2:0',
      'anthropic.claude-3-5-haiku-20241022-v1:0',
      'cohere.command-r-plus-v1:0',
      'cohere.command-r-v1:0',
      'meta.llama3-70b-instruct-v1:0',
      'meta.llama3-8b-instruct-v1:0',
      'mistral.mistral-large-2402-v1:0',
      'amazon.titan-text-express-v1',
    ] as const,
    // At the time of writing, the only models that Bedrock supports which allow JSON are Mistral
    // models. However, Bedrock's `additionalModelRequestFields` field, which is designed to allow
    // us to pass arbitrary parameters to the model, does not appear to work for Mistral's
    // `responseFormat` field.
    supportsJSON: [],
    supportsImages: [
      'anthropic.claude-3-5-sonnet-20241022-v2:0',
      'anthropic.claude-3-5-haiku-20241022-v1:0',
    ] as const,
    supportsToolCalls: [
      'anthropic.claude-3-5-sonnet-20241022-v2:0',
      'anthropic.claude-3-5-haiku-20241022-v1:0',
      'cohere.command-r-plus-v1:0',
      'cohere.command-r-v1:0',
      'mistral.mistral-large-2402-v1:0',
    ] as const,
    supportsN: false,
    generateDocs: true,
  },
  mistral: {
    models: [
      'mistral-large-2411',
      'magistral-medium-2509',
      'magistral-small-2509',
      'pixtral-large-2411',
      'pixtral-12b-2409',
      'codestral-2508',
      'mistral-small-2506',
      'mistral-nemo-2407',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'mistral-large-2411',
      'magistral-medium-2509',
      'magistral-small-2509',
      'pixtral-large-2411',
      'pixtral-12b-2409',
      'codestral-2508',
      'mistral-small-2506',
      'mistral-nemo-2407',
    ] as const,
    // Mistral claims that all of its models support JSON, but several of their weaker models either
    // fail to produce valid JSON or produce very low quality results for the following prompt:
    // "Generate a JSON that maps ten athletes to their jersey numbers". We removed these models
    // from the list to ensure that we only support models that reliably produce decent results.
    supportsJSON: [
      'mistral-large-2411',
      'codestral-2508',
    ] as const,
    supportsImages: [
      'magistral-medium-2509',
      'magistral-small-2509',
      'pixtral-large-2411',
      'pixtral-12b-2409',
      'mistral-small-2506',
    ] as const,
    supportsToolCalls: [
      'mistral-large-2411',
      'mistral-small-2506',
    ] as const,
    supportsN: false,
    generateDocs: true,
  },
  groq: {
    models: [
      'meta-llama/llama-4-maverick-17b-128e-instruct',
      'meta-llama/llama-4-scout-17b-16e-instruct',
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'moonshotai/kimi-k2-instruct-0905',
      'qwen/qwen3-32b',
      'openai/gpt-oss-120b',
      'whisper-large-v3-turbo',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'meta-llama/llama-4-maverick-17b-128e-instruct',
      'meta-llama/llama-4-scout-17b-16e-instruct',
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'moonshotai/kimi-k2-instruct-0905',
      'qwen/qwen3-32b',
      'openai/gpt-oss-120b',
    ] as const,
    // Groq claims that all of its models support JSON, but some of the weaker models either fail to
    // produce valid JSON or produce very low quality results for the following prompt: "Generate a
    // JSON that maps ten athletes to their jersey numbers". We removed these models from the list
    // to ensure that we only support models that reliably produce decent results.
    supportsJSON: [
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'openai/gpt-oss-120b',
    ] as const,
    supportsImages: [
      'meta-llama/llama-4-maverick-17b-128e-instruct',
      'meta-llama/llama-4-scout-17b-16e-instruct',
    ] as const,
    supportsToolCalls: [] as const,
    supportsN: false,
    generateDocs: true,
  },
  perplexity: {
    models: [
      'sonar',
      'sonar-pro',
      'sonar-reasoning-pro',
    ] as const,
    supportsCompletion: true,
    supportsStreaming: [
      'sonar',
      'sonar-pro',
      'sonar-reasoning-pro',
    ] as const,
    supportsJSON: [
      'sonar',
      'sonar-pro',
      'sonar-reasoning-pro',
    ] as const,
    supportsImages: [] as const,
    supportsToolCalls: [
      'sonar',
      'sonar-pro',
      'sonar-reasoning-pro',
    ] as const,
    supportsN: false,
    generateDocs: true,
  },
  openrouter: {
    models: true,
    supportsCompletion: true,
    supportsStreaming: true,
    supportsJSON: true,
    supportsImages: true,
    supportsToolCalls: true,
    supportsN: true,
    generateDocs: false,
  },
  'openai-compatible': {
    models: true,
    supportsCompletion: true,
    supportsStreaming: true,
    supportsJSON: true,
    supportsImages: true,
    supportsToolCalls: true,
    supportsN: true,
    generateDocs: false,
  },
}
